## Семинар 7
# Тема: Отбор наилучшей модели из нескольких с наилучшими гиперпараметрами поиском по сетке

---

### Цель работы

Научиться выбирать наилучшую модель классификации из нескольких кандидатов с одновременным подбором гиперпараметров с помощью `GridSearchCV` и `Pipeline`.

## Теоретическая справка

### Проблема выбора модели

На практике заранее неизвестно, какой алгоритм подойдёт для конкретной задачи лучше всего. Поэтому применяют **одновременный перебор** нескольких моделей и их гиперпараметров. Это позволяет избежать ручного последовательного сравнения и получить статистически обоснованный выбор.

Ключевая идея: включить **сам класс модели** в пространство поиска наряду с её гиперпараметрами.

---

### Pipeline

[`Pipeline`](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html) — объект scikit-learn, объединяющий несколько шагов обработки данных и финальную модель в единую цепочку:

```
Данные → Шаг 1 (Scaler) → Шаг 2 (Encoder) → ... → Финальная модель
```

**Преимущества Pipeline:**

| Преимущество | Пояснение |
|---|---|
| Защита от утечки данных | Scaler обучается только на `X_train`, не видит `X_test` |
| Единый API | `fit`, `predict`, `score` работают как у обычной модели |
| Совместимость с GridSearchCV | Гиперпараметры любого шага доступны через `шаг__параметр` |
| Воспроизводимость | Весь процесс инкапсулирован в одном объекте |

**Синтаксис создания Pipeline:**

```python
pipe = Pipeline([
    ('scaler', StandardScaler()),   # шаг 1: масштабирование
    ('classifier', SVC())           # шаг 2: классификатор
])
```

Доступ к гиперпараметрам шага осуществляется через двойное подчёркивание: `шаг__параметр`. Например: `classifier__C`, `scaler__with_mean`.

---

### GridSearchCV

[`GridSearchCV`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) выполняет исчерпывающий перебор всех комбинаций указанных гиперпараметров с оценкой качества через кросс-валидацию.

**Схема работы:**

```
Для каждой комбинации гиперпараметров:
    Разделить обучающие данные на cv фолдов
    Для каждого фолда:
        Обучить модель на (cv-1) фолдах
        Оценить на оставшемся фолде
    Усреднить оценку по всем фолдам
Выбрать комбинацию с наилучшей средней оценкой
Переобучить на всей обучающей выборке с лучшими параметрами
```

**Ключевые параметры GridSearchCV:**

| Параметр | Описание | Рекомендуемые значения |
|---|---|---|
| `estimator` | Модель или Pipeline | Любой объект sklearn |
| `param_grid` | Словарь или список словарей гиперпараметров | dict или list[dict] |
| `cv` | Число фолдов кросс-валидации | 5 (по умолчанию) |
| `scoring` | Метрика оценки | `'accuracy'`, `'f1'`, `'roc_auc'`, ... |
| `refit` | Переобучить лучшую модель на всех данных | `True` (по умолчанию) |
| `n_jobs` | Число параллельных задач | `-1` (все ядра) |
| `return_train_score` | Сохранять ли train score | `True` для диагностики |

**Ключевые атрибуты после обучения:**

| Атрибут | Описание |
|---|---|
| `best_params_` | Словарь лучших гиперпараметров |
| `best_score_` | Лучшее среднее CV-качество |
| `best_estimator_` | Переобученная лучшая модель |
| `cv_results_` | Подробная таблица всех экспериментов |

---

### Выбор модели через Pipeline + GridSearchCV

Чтобы перебирать **разные классы моделей**, шаг классификатора задаётся как гиперпараметр Pipeline. Тогда `param_grid` становится **списком словарей**, каждый из которых соответствует одной модели:

```python
pipe = Pipeline([('classifier', SVC())])  # placeholder

param_grid = [
    {'classifier': [SVC()],
     'classifier__C': [0.1, 1, 10]},

    {'classifier': [DecisionTreeClassifier()],
     'classifier__max_depth': [3, 5, 10]}
]

grid = GridSearchCV(pipe, param_grid, cv=5)
grid.fit(X_train, y_train)
```

⚠️ **Важно:** GridSearchCV итерирует по словарям в `param_grid` независимо, поэтому параметры одной модели не смешиваются с параметрами другой.

---

### Добавление предобработки в Pipeline

Масштабирование нужно **не всем** моделям одинаково. Решения:

**Вариант 1.** Единый Scaler для всего Pipeline (применяется ко всем моделям):
```python
pipe = Pipeline([('scaler', MinMaxScaler()), ('classifier', SVC())])
```

**Вариант 2.** Вложенный Pipeline для конкретной модели:
```python
param_svc = {'classifier': [make_pipeline(MinMaxScaler(), SVC())],
             'classifier__svc__C': [0.1, 1, 10]}
param_tree = {'classifier': [DecisionTreeClassifier()],
              'classifier__max_depth': [3, 5, 10]}
```

Вариант 2 предпочтителен, когда одна модель требует масштабирования (SVM, KNN), а другая — нет (деревья, случайный лес).

---

### Дополнительные ресурсы

- 📖 [Pipeline — документация sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html)
- 📖 [GridSearchCV — документация sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html)
- 📖 [User Guide: Pipelines and composite estimators](https://scikit-learn.org/stable/modules/compose.html)
- 📖 [User Guide: Tuning the hyper-parameters of an estimator](https://scikit-learn.org/stable/modules/grid_search.html)

---

Рассмотрим следующую задачу: необходимо подобрать наилучшую модель (из нескольких) с наилучшими гиперпараметрами, а затем для выбранной модели оценить качество обобщающей способности. Это можно сделать с помощью поиска по сетке, в которой присутствует и вид модели тоже (а не только значения гиперпараметров модели) с перекрёстной проверкой.

Импортируем необходимые библиотеки:

In [25]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris, load_breast_cancer
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn import metrics
from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.model_selection import GridSearchCV

### 1. Загрузите встроенный датасет load_breast_cancer. Обозначьте признаки за X, а целевую переменную за y и выведите их размеры. Выведите данные в виде датафрейма.

In [26]:
cancer= load_breast_cancer()
X=cancer.data
y=cancer.target
X.shape,y.shape

((569, 30), (569,))

In [27]:
df=pd.DataFrame(X,columns=cancer.feature_names)
df['target']=y
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [28]:
df['target'].value_counts()

target
1    357
0    212
Name: count, dtype: int64

### 2. Разбейте данные на два набора обучающий и тестовый при помощи train_test_split, зафиксировав random_state=0. Выведите размеры полученных наборов.

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)
X_train.shape[0],X_test.shape[0]

(426, 143)

### 3. Используя GridSearchCV, подберите наилучшую модель классификатора на обучающем наборе данных, выбирая между методом опорных векторов и деревом решений, подобрав наилучшие гиперпараметры для этих моделей, используя следующие сетки гиперпараметров. Выведите получившуюся модель с наилучшими значениями гиперпараметров.

In [30]:
param_svc= {'classifier': [SVC()], 
            'classifier__C': [0.001, 0.01, 0.1, 1, 10, 100]}
param_tree = {'classifier': [DecisionTreeClassifier(random_state = 42)],
              "classifier__max_depth": [1, 3, 5, 7, 10],
              "classifier__min_samples_leaf": [1, 3, 5, 10],
              "classifier__criterion": ["gini", "entropy"]}

In [31]:
param_grid=[param_svc,param_tree]

In [32]:
pipeline=Pipeline([('classifier',SVC())])

In [33]:
gs=GridSearchCV(pipeline,param_grid,cv=5,n_jobs=-1)

In [34]:
gs.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=Pipeline(steps=[('classifier', SVC())]), n_jobs=-1,
             param_grid=[{'classifier': [SVC()],
                          'classifier__C': [0.001, 0.01, 0.1, 1, 10, 100]},
                         {'classifier': [DecisionTreeClassifier(random_state=42)],
                          'classifier__criterion': ['gini', 'entropy'],
                          'classifier__max_depth': [1, 3, 5, 7, 10],
                          'classifier__min_samples_leaf': [1, 3, 5, 10]}])

In [35]:
df=pd.DataFrame(gs.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_classifier,param_classifier__C,param_classifier__criterion,param_classifier__max_depth,param_classifier__min_samples_leaf,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003912,0.001469,0.002198,0.000820,SVC(),0.001,NaN,NaN,NaN,"{'classifier': SVC(), 'classifier__C': 0.001}",0.627907,0.635294,0.623529,0.623529,0.623529,0.626758,0.004593,46
1,0.003622,0.001249,0.002425,0.001002,SVC(),0.010,NaN,NaN,NaN,"{'classifier': SVC(), 'classifier__C': 0.01}",0.627907,0.670588,0.658824,0.682353,0.670588,0.662052,0.018623,45
2,0.002600,0.000890,0.001518,0.000604,SVC(),0.100,NaN,NaN,NaN,"{'classifier': SVC(), 'classifier__C': 0.1}",0.895349,0.858824,0.882353,0.870588,0.894118,0.880246,0.013980,44
3,0.002958,0.000313,0.001712,0.000103,SVC(),1.000,NaN,NaN,NaN,"{'classifier': SVC(), 'classifier__C': 1}",0.918605,0.870588,0.905882,0.882353,0.917647,0.899015,0.019307,35
4,0.002221,0.000584,0.001287,0.000414,SVC(),10.000,NaN,NaN,NaN,"{'classifier': SVC(), 'classifier__C': 10}",0.965116,0.882353,0.905882,0.917647,0.905882,0.915376,0.027386,22
5,0.002506,0.000673,0.001164,0.000346,SVC(),100.000,NaN,NaN,NaN,"{'classifier': SVC(), 'classifier__C': 100}",0.976744,0.894118,0.941176,0.905882,0.929412,0.929466,0.028907,2
6,0.001636,0.000595,0.000441,0.000234,DecisionTreeClassifier(random_state=42),NaN,gini,1.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,36
7,0.001415,0.000419,0.000307,0.000123,DecisionTreeClassifier(random_state=42),NaN,gini,1.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,36
8,0.001794,0.000567,0.000462,0.000248,DecisionTreeClassifier(random_state=42),NaN,gini,1.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,36
9,0.002054,0.000461,0.000532,0.000191,DecisionTreeClassifier(random_state=42),NaN,gini,1.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,36
10,0.004105,0.000172,0.000587,0.000152,DecisionTreeClassifier(random_state=42),NaN,gini,3.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.895349,0.905882,0.941176,0.929412,0.882353,0.910834,0.021639,25
11,0.002644,0.000650,0.000281,0.000036,DecisionTreeClassifier(random_state=42),NaN,gini,3.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.905882,0.929412,0.929412,0.882353,0.910807,0.017555,26
12,0.003070,0.000447,0.000386,0.000136,DecisionTreeClassifier(random_state=42),NaN,gini,3.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.905882,0.929412,0.905882,0.882353,0.906101,0.014888,30
13,0.002513,0.000559,0.000387,0.000145,DecisionTreeClassifier(random_state=42),NaN,gini,3.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.905882,0.929412,0.917647,0.917647,0.915513,0.008578,17
14,0.003329,0.000802,0.000278,0.000055,DecisionTreeClassifier(random_state=42),NaN,gini,5.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.905882,0.941176,0.929412,0.882353,0.913160,0.020442,24
15,0.003734,0.000800,0.000436,0.000233,DecisionTreeClassifier(random_state=42),NaN,gini,5.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.930233,0.941176,0.917647,0.917647,0.941176,0.929576,0.010528,1
16,0.004302,0.000838,0.000525,0.000205,DecisionTreeClassifier(random_state=42),NaN,gini,5.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.918605,0.952941,0.894118,0.905882,0.917647,0.917839,0.019690,15
17,0.003576,0.001113,0.000514,0.000242,DecisionTreeClassifier(random_state=42),NaN,gini,5.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.917647,0.929412,0.917647,0.917647,0.917866,0.007100,12
18,0.003849,0.000809,0.000355,0.000188,DecisionTreeClassifier(random_state=42),NaN,gini,7.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.894118,0.929412,0.905882,0.929412,0.913160,0.014015,23
19,0.003423,0.000762,0.000379,0.000217,DecisionTreeClassifier(random_state=42),NaN,gini,7.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.930233,0.905882,0.917647,0.905882,0.952941,0.922517,0.017677,3
20,0.003099,0.001138,0.000258,0.000044,DecisionTreeClassifier(random_state=42),NaN,gini,7.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.918605,0.952941,0.894118,0.894118,0.917647,0.915486,0.021589,18
21,0.002705,0.000524,0.000238,0.000038,DecisionTreeClassifier(random_state=42),NaN,gini,7.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.917647,0.929412,0.917647,0.917647,0.917866,0.007100,12
22,0.003491,0.000713,0.000346,0.000140,DecisionTreeClassifier(random_state=42),NaN,gini,10.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.894118,0.929412,0.905882,0.905882,0.908454,0.011491,27
23,0.003302,0.000972,0.000377,0.000191,DecisionTreeClassifier(random_state=42),NaN,gini,10.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.930233,0.905882,0.917647,0.905882,0.952941,0.922517,0.017677,3
24,0.002514,0.000101,0.000218,0.000032,DecisionTreeClassifier(random_state=42),NaN,gini,10.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.918605,0.952941,0.894118,0.894118,0.917647,0.915486,0.021589,18
25,0.002670,0.000509,0.000223,0.000049,DecisionTreeClassifier(random_state=42),NaN,gini,10.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.917647,0.929412,0.917647,0.917647,0.917866,0.007100,12
26,0.001796,0.000810,0.000283,0.000145,DecisionTreeClassifier(random_state=42),NaN,entropy,1.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,36
27,0.001808,0.000801,0.000336,0.000166,DecisionTreeClassifier(random_state=42),NaN,entropy,1.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,36
28,0.002244,0.000545,0.000438,0.000149,DecisionTreeClassifier(random_state=42),NaN,entropy,1.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,36
29,0.001712,0.000672,0.000384,0.000235,DecisionTreeClassifier(random_state=42),NaN,entropy,1.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,36
30,0.003627,0.001116,0.000419,0.000195,DecisionTreeClassifier(random_state=42),NaN,entropy,3.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.905882,0.929412,0.917647,0.905882,0.922462,0.017798,5
31,0.002257,0.000046,0.000203,0.000019,DecisionTreeClassifier(random_state=42),NaN,entropy,3.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.905882,0.929412,0.917647,0.905882,0.922462,0.017798,5
32,0.003760,0.001325,0.000369,0.000162,DecisionTreeClassifier(random_state=42),NaN,entropy,3.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.905882,0.929412,0.917647,0.905882,0.922462,0.017798,5
33,0.003336,0.001236,0.000449,0.000160,DecisionTreeClassifier(random_state=42),NaN,entropy,3.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.905882,0.917647,0.917647,0.870588,0.903748,0.017326,31
34,0.003396,0.001047,0.000247,0.000041,DecisionTreeClassifier(random_state=42),NaN,entropy,5.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.905882,0.882353,0.952941,0.894118,0.917756,0.029893,16
35,0.004269,0.001105,0.000452,0.000167,DecisionTreeClassifier(random_state=42),NaN,entropy,5.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.965116,0.929412,0.882353,0.929412,0.894118,0.920082,0.029325,11
36,0.003547,0.001416,0.000285,0.000119,DecisionTreeClassifier(random_state=42),NaN,entropy,5.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.952941,0.929412,0.882353,0.882353,0.920109,0.032030,8
37,0.002344,0.000210,0.000218,0.000037,DecisionTreeClassifier(random_state=42),NaN,entropy,5.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.917647,0.917647,0.905882,0.870588,0.903748,0.017326,31
38,0.003459,0.001114,0.000314,0.000150,DecisionTreeClassifier(random_state=42),NaN,entropy,7.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.882353,0.882353,0.952941,0.870588,0.908345,0.036888,28
39,0.002905,0.001061,0.000214,0.000055,DecisionTreeClassifier(random_state=42),NaN,entropy,7.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.965116,0.929412,0.882353,0.929412,0.870588,0.915376,0.034539,20
40,0.003889,0.000860,0.000295,0.000040,DecisionTreeClassifier(random_state=42),NaN,entropy,7.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.952941,0.929412,0.882353,0.882353,0.920109,0.032030,8
41,0.002780,0.000334,0.000284,0.000020,DecisionTreeClassifier(random_state=42),NaN,entropy,7.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.917647,0.917647,0.905882,0.870588,0.903748,0.017326,31
42,0.002797,0.000232,0.000251,0.000027,DecisionTreeClassifier(random_state=42),NaN,entropy,10.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.882353,0.882353,0.952941,0.870588,0.908345,0.036888,28
43,0.003564,0.000628,0.000298,0.000034,DecisionTreeClassifier(random_state=42),NaN,entropy,10.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.965116,0.929412,0.882353,0.929412,0.870588,0.915376,0.034539,20
44,0.003256,0.000563,0.000365,0.000177,DecisionTreeClassifier(random_state=42),NaN,entropy,10.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.952941,0.929412,0.882353,0.882353,0.920109,0.032030,8
45,0.002893,0.000217,0.000251,0.000032,DecisionTreeClassifier(random_state=42),NaN,entropy,10.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.917647,0.917647,0.905882,0.870588,0.903748,0.017326,31

In [36]:
df[['params','mean_test_score']]

                                               params  mean_test_score
0       {'classifier': SVC(), 'classifier__C': 0.001}         0.626758
1        {'classifier': SVC(), 'classifier__C': 0.01}         0.662052
2         {'classifier': SVC(), 'classifier__C': 0.1}         0.880246
3           {'classifier': SVC(), 'classifier__C': 1}         0.899015
4          {'classifier': SVC(), 'classifier__C': 10}         0.915376
5         {'classifier': SVC(), 'classifier__C': 100}         0.929466
6   {'classifier': DecisionTreeClassifier(random_s...         0.887332
7   {'classifier': DecisionTreeClassifier(random_s...         0.887332
8   {'classifier': DecisionTreeClassifier(random_s...         0.887332
9   {'classifier': DecisionTreeClassifier(random_s...         0.887332
10  {'classifier': DecisionTreeClassifier(random_s...         0.910834
11  {'classifier': DecisionTreeClassifier(random_s...         0.910807
12  {'classifier': DecisionTreeClassifier(random_s...         0.906101
13  {'classifier': DecisionTreeClassifier(random_s...         0.915513
14  {'classifier': DecisionTreeClassifier(random_s...         0.913160
15  {'classifier': DecisionTreeClassifier(random_s...         0.929576
16  {'classifier': DecisionTreeClassifier(random_s...         0.917839
17  {'classifier': DecisionTreeClassifier(random_s...         0.917866
18  {'classifier': DecisionTreeClassifier(random_s...         0.913160
19  {'classifier': DecisionTreeClassifier(random_s...         0.922517
20  {'classifier': DecisionTreeClassifier(random_s...         0.915486
21  {'classifier': DecisionTreeClassifier(random_s...         0.917866
22  {'classifier': DecisionTreeClassifier(random_s...         0.908454
23  {'classifier': DecisionTreeClassifier(random_s...         0.922517
24  {'classifier': DecisionTreeClassifier(random_s...         0.915486
25  {'classifier': DecisionTreeClassifier(random_s...         0.917866
26  {'classifier': DecisionTreeClassifier(random_s...         0.887332
27  {'classifier': DecisionTreeClassifier(random_s...         0.887332
28  {'classifier': DecisionTreeClassifier(random_s...         0.887332
29  {'classifier': DecisionTreeClassifier(random_s...         0.887332
30  {'classifier': DecisionTreeClassifier(random_s...         0.922462
31  {'classifier': DecisionTreeClassifier(random_s...         0.922462
32  {'classifier': DecisionTreeClassifier(random_s...         0.922462
33  {'classifier': DecisionTreeClassifier(random_s...         0.903748
34  {'classifier': DecisionTreeClassifier(random_s...         0.917756
35  {'classifier': DecisionTreeClassifier(random_s...         0.920082
36  {'classifier': DecisionTreeClassifier(random_s...         0.920109
37  {'classifier': DecisionTreeClassifier(random_s...         0.903748
38  {'classifier': DecisionTreeClassifier(random_s...         0.908345
39  {'classifier': DecisionTreeClassifier(random_s...         0.915376
40  {'classifier': DecisionTreeClassifier(random_s...         0.920109
41  {'classifier': DecisionTreeClassifier(random_s...         0.903748
42  {'classifier': DecisionTreeClassifier(random_s...         0.908345
43  {'classifier': DecisionTreeClassifier(random_s...         0.915376
44  {'classifier': DecisionTreeClassifier(random_s...         0.920109
45  {'classifier': DecisionTreeClassifier(random_s...         0.903748

In [37]:
gs.best_params_

{'classifier': DecisionTreeClassifier(random_state=42),
 'classifier__criterion': 'gini',
 'classifier__max_depth': 5,
 'classifier__min_samples_leaf': 3}

### 4. Оцените качество наилучшей модели, выведя значения метрик accuracy и f1-score на тестовых данных.

In [38]:
y_pred=gs.predict(X_test)
accuracy=metrics.accuracy_score(y_test,y_pred)
accuracy

0.9300699300699301

### 5. Добавьте масштабирование данных методом min-max в метод опорных векторов и снова подберите наилучшую модель классификатора, выбирая между методом опорных векторов и деревом решений с теми же диапазонами гиперпараметров. Выведите получившуюся модель с наилучшими значениями гиперпараметров.

In [39]:
param_svc= {'classifier': [SVC()], 
            'scaler':[MinMaxScaler()],
            'classifier__C': [0.001, 0.01, 0.1, 1, 10, 100]}
param_tree = {'classifier': [DecisionTreeClassifier(random_state = 42)],
              'scaler':[None],
              "classifier__max_depth": [1, 3, 5, 7, 10],
              "classifier__min_samples_leaf": [1, 3, 5, 10],
              "classifier__criterion": ["gini", "entropy"]}

In [40]:
param_grid=[param_svc,param_tree]

In [41]:
pipe=Pipeline([('scaler',MinMaxScaler()),('classifier',SVC())])

In [42]:
gs_new=GridSearchCV(pipe,param_grid,cv=5,n_jobs=-1)
gs_new.fit(X_train,y_train)

df_new=pd.DataFrame(gs_new.cv_results_)
df_new

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_classifier,param_classifier__C,param_scaler,param_classifier__criterion,param_classifier__max_depth,param_classifier__min_samples_leaf,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002737,0.000187,0.001387,0.000135,SVC(),0.001,MinMaxScaler(),NaN,NaN,NaN,"{'classifier': SVC(), 'classifier__C': 0.001, ...",0.627907,0.635294,0.623529,0.623529,0.623529,0.626758,0.004593,45
1,0.002365,0.000189,0.001286,0.000078,SVC(),0.010,MinMaxScaler(),NaN,NaN,NaN,"{'classifier': SVC(), 'classifier__C': 0.01, '...",0.627907,0.635294,0.623529,0.623529,0.623529,0.626758,0.004593,45
2,0.001566,0.000089,0.000909,0.000182,SVC(),0.100,MinMaxScaler(),NaN,NaN,NaN,"{'classifier': SVC(), 'classifier__C': 0.1, 's...",0.895349,0.964706,0.941176,0.952941,0.976471,0.946129,0.027983,4
3,0.001356,0.000208,0.000583,0.000060,SVC(),1.000,MinMaxScaler(),NaN,NaN,NaN,"{'classifier': SVC(), 'classifier__C': 1, 'sca...",0.976744,0.976471,0.952941,1.000000,1.000000,0.981231,0.017594,1
4,0.001224,0.000142,0.000463,0.000021,SVC(),10.000,MinMaxScaler(),NaN,NaN,NaN,"{'classifier': SVC(), 'classifier__C': 10, 'sc...",1.000000,0.964706,0.952941,0.988235,0.988235,0.978824,0.017291,2
5,0.001080,0.000069,0.000428,0.000063,SVC(),100.000,MinMaxScaler(),NaN,NaN,NaN,"{'classifier': SVC(), 'classifier__C': 100, 's...",0.976744,0.941176,0.929412,0.976471,0.941176,0.952996,0.019752,3
6,0.001418,0.000278,0.000332,0.000112,DecisionTreeClassifier(random_state=42),NaN,None,gini,1.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,37
7,0.001251,0.000133,0.000321,0.000131,DecisionTreeClassifier(random_state=42),NaN,None,gini,1.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,37
8,0.001100,0.000080,0.000218,0.000022,DecisionTreeClassifier(random_state=42),NaN,None,gini,1.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,37
9,0.001337,0.000190,0.000271,0.000047,DecisionTreeClassifier(random_state=42),NaN,None,gini,1.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,37
10,0.002591,0.000717,0.000363,0.000150,DecisionTreeClassifier(random_state=42),NaN,None,gini,3.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.895349,0.905882,0.941176,0.929412,0.882353,0.910834,0.021639,27
11,0.002390,0.000289,0.000350,0.000191,DecisionTreeClassifier(random_state=42),NaN,None,gini,3.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.905882,0.929412,0.929412,0.882353,0.910807,0.017555,28
12,0.002374,0.000204,0.000301,0.000020,DecisionTreeClassifier(random_state=42),NaN,None,gini,3.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.905882,0.929412,0.905882,0.882353,0.906101,0.014888,32
13,0.002994,0.000698,0.000383,0.000163,DecisionTreeClassifier(random_state=42),NaN,None,gini,3.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.905882,0.929412,0.917647,0.917647,0.915513,0.008578,20
14,0.003367,0.000841,0.000272,0.000061,DecisionTreeClassifier(random_state=42),NaN,None,gini,5.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.905882,0.941176,0.929412,0.882353,0.913160,0.020442,26
15,0.003565,0.000610,0.000447,0.000232,DecisionTreeClassifier(random_state=42),NaN,None,gini,5.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.930233,0.941176,0.917647,0.917647,0.941176,0.929576,0.010528,5
16,0.003563,0.000816,0.000442,0.000140,DecisionTreeClassifier(random_state=42),NaN,None,gini,5.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.918605,0.952941,0.894118,0.905882,0.917647,0.917839,0.019690,18
17,0.003645,0.000595,0.000481,0.000161,DecisionTreeClassifier(random_state=42),NaN,None,gini,5.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.917647,0.929412,0.917647,0.917647,0.917866,0.007100,15
18,0.004472,0.001771,0.000487,0.000162,DecisionTreeClassifier(random_state=42),NaN,None,gini,7.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.894118,0.929412,0.905882,0.929412,0.913160,0.014015,25
19,0.003642,0.000953,0.000290,0.000055,DecisionTreeClassifier(random_state=42),NaN,None,gini,7.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.930233,0.905882,0.917647,0.905882,0.952941,0.922517,0.017677,6
20,0.003411,0.000715,0.000410,0.000152,DecisionTreeClassifier(random_state=42),NaN,None,gini,7.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.918605,0.952941,0.894118,0.894118,0.917647,0.915486,0.021589,21
21,0.002381,0.000197,0.000339,0.000176,DecisionTreeClassifier(random_state=42),NaN,None,gini,7.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.917647,0.929412,0.917647,0.917647,0.917866,0.007100,15
22,0.003718,0.001288,0.000267,0.000039,DecisionTreeClassifier(random_state=42),NaN,None,gini,10.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.894118,0.929412,0.905882,0.905882,0.908454,0.011491,29
23,0.002863,0.000361,0.000322,0.000131,DecisionTreeClassifier(random_state=42),NaN,None,gini,10.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.930233,0.905882,0.917647,0.905882,0.952941,0.922517,0.017677,6
24,0.002938,0.000304,0.000286,0.000048,DecisionTreeClassifier(random_state=42),NaN,None,gini,10.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.918605,0.952941,0.894118,0.894118,0.917647,0.915486,0.021589,21
25,0.002570,0.000454,0.000323,0.000151,DecisionTreeClassifier(random_state=42),NaN,None,gini,10.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.917647,0.929412,0.917647,0.917647,0.917866,0.007100,15
26,0.001514,0.000498,0.000350,0.000175,DecisionTreeClassifier(random_state=42),NaN,None,entropy,1.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,37
27,0.002087,0.000490,0.000475,0.000178,DecisionTreeClassifier(random_state=42),NaN,None,entropy,1.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,37
28,0.001942,0.000680,0.000353,0.000198,DecisionTreeClassifier(random_state=42),NaN,None,entropy,1.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,37
29,0.001967,0.000685,0.000527,0.000172,DecisionTreeClassifier(random_state=42),NaN,None,entropy,1.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.883721,0.894118,0.894118,0.905882,0.858824,0.887332,0.015887,37
30,0.003626,0.001237,0.000421,0.000269,DecisionTreeClassifier(random_state=42),NaN,None,entropy,3.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.905882,0.929412,0.917647,0.905882,0.922462,0.017798,8
31,0.003146,0.000516,0.000404,0.000162,DecisionTreeClassifier(random_state=42),NaN,None,entropy,3.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.905882,0.929412,0.917647,0.905882,0.922462,0.017798,8
32,0.002730,0.000248,0.000287,0.000035,DecisionTreeClassifier(random_state=42),NaN,None,entropy,3.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.905882,0.929412,0.917647,0.905882,0.922462,0.017798,8
33,0.003704,0.000508,0.000465,0.000178,DecisionTreeClassifier(random_state=42),NaN,None,entropy,3.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.905882,0.917647,0.917647,0.870588,0.903748,0.017326,33
34,0.003166,0.000409,0.000339,0.000131,DecisionTreeClassifier(random_state=42),NaN,None,entropy,5.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.905882,0.882353,0.952941,0.894118,0.917756,0.029893,19
35,0.003617,0.000970,0.000298,0.000037,DecisionTreeClassifier(random_state=42),NaN,None,entropy,5.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.965116,0.929412,0.882353,0.929412,0.894118,0.920082,0.029325,14
36,0.003478,0.000523,0.000445,0.000158,DecisionTreeClassifier(random_state=42),NaN,None,entropy,5.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.952941,0.929412,0.882353,0.882353,0.920109,0.032030,11
37,0.003370,0.000845,0.000470,0.000214,DecisionTreeClassifier(random_state=42),NaN,None,entropy,5.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.917647,0.917647,0.905882,0.870588,0.903748,0.017326,33
38,0.003094,0.000338,0.000265,0.000033,DecisionTreeClassifier(random_state=42),NaN,None,entropy,7.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.882353,0.882353,0.952941,0.870588,0.908345,0.036888,30
39,0.003128,0.000476,0.000300,0.000020,DecisionTreeClassifier(random_state=42),NaN,None,entropy,7.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.965116,0.929412,0.882353,0.929412,0.870588,0.915376,0.034539,23
40,0.003268,0.000446,0.000290,0.000036,DecisionTreeClassifier(random_state=42),NaN,None,entropy,7.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.952941,0.929412,0.882353,0.882353,0.920109,0.032030,11
41,0.002831,0.000405,0.000320,0.000111,DecisionTreeClassifier(random_state=42),NaN,None,entropy,7.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.917647,0.917647,0.905882,0.870588,0.903748,0.017326,33
42,0.003370,0.000684,0.000354,0.000140,DecisionTreeClassifier(random_state=42),NaN,None,entropy,10.0,1.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.882353,0.882353,0.952941,0.870588,0.908345,0.036888,30
43,0.003510,0.001047,0.000266,0.000038,DecisionTreeClassifier(random_state=42),NaN,None,entropy,10.0,3.0,{'classifier': DecisionTreeClassifier(random_s...,0.965116,0.929412,0.882353,0.929412,0.870588,0.915376,0.034539,23
44,0.003172,0.000571,0.000390,0.000168,DecisionTreeClassifier(random_state=42),NaN,None,entropy,10.0,5.0,{'classifier': DecisionTreeClassifier(random_s...,0.953488,0.952941,0.929412,0.882353,0.882353,0.920109,0.032030,11
45,0.002979,0.000510,0.000267,0.000028,DecisionTreeClassifier(random_state=42),NaN,None,entropy,10.0,10.0,{'classifier': DecisionTreeClassifier(random_s...,0.906977,0.917647,0.917647,0.905882,0.870588,0.903748,0.017326,33

In [44]:
gs_new.best_params_

{'classifier': SVC(), 'classifier__C': 1, 'scaler': MinMaxScaler()}

In [45]:
best_estimator=gs_new.best_estimator_
best_estimator

Pipeline(steps=[('scaler', MinMaxScaler()), ('classifier', SVC(C=1))])

### 6. Оцените качество полученной наилучшей модели с учётом масштабирования данных, выведя значения метрик accuracy и f1-score на тестовых данных. Сделайте вывод о том нужно ли было делать масштабирование данных.

In [46]:
y_pred=gs_new.predict(X_test)
accuracy=metrics.accuracy_score(y_test,y_pred)
f1=metrics.f1_score(y_test,y_pred)
accuracy,f1

(0.972027972027972, 0.978021978021978)

## Задания для самостоятельного выполнения
1. Загрузите встроенный датасет `load_iris`. Обозначьте данные за `X`, а целевую переменную за `y`.
2. Разбейте данные на два набора: обучающий и тестовый, взяв в тестовый набор 20% данных и указав random_state=0.
3. Используя `GridSearchCV`, подберите наилучшую модель классификатора на обучающем наборе данных, выбирая между методом логистической регрессии и деревом со следующими наборами гиперпараметров: param_grid = [{'classifier': [LogisticRegression(max_iter=500)],'classifier__C': np.logspace(0,4,10), 'classifier__penalty': ['l2', 'l1'], 'classifier__solver': ['liblinear']}, {'classifier': [LogisticRegression(max_iter=500)],'classifier__C': np.logspace(0,4,10), 'classifier__penalty': ['l2'], 'classifier__solver': ['lbfgs', 'newton-cg']}, {'classifier': [DecisionTreeClassifier(random_state = 42)], 'classifier__max_depth': [1, 3, 5, 7], 'classifier__criterion': ["gini", "entropy"], 'classifier__max_features': [1, 2, 3]}]. Выведите получившуюся модель с наилучшими значениями гиперпараметров.
4. Оцените качество наилучшей модели, выведя значения метрик accuracy и f1-score на тестовых данных.
5. Добавьте стандартную нормализацию данных в метод логистической регрессии и снова подберите наилучшую модель классификатора, выбирая между методом логистической регрессии и деревом решений с теми же диапазонами гиперпараметров. Выведите получившуюся модель с наилучшими значениями гиперпараметров.
6. Оцените качество полученной наилучшей модели с учётом стандартной нормализации данных, выведя значения метрик accuracy и f1-score на тестовых данных. Сделайте вывод о том нужна ли здесь была нормализация данных.